set_property SRC_FILE_INFO {cfile:d:/FPGA-MAZE-2023DD-final/FPGA-MAZE-vivado/FPGA-MAZE-vivado.gen/sources_1/ip/background_rom_1/background_rom/background_rom_in_context.xdc rfile:../../../../../FPGA-MAZE-vivado.gen/sources_1/ip/background_rom_1/background_rom/background_rom_in_context.xdc id:1 order:EARLY scoped_inst:graphics/draw/background_inst/background_rom_inst} [current_design]
set_property SRC_FILE_INFO {cfile:d:/FPGA-MAZE-2023DD-final/FPGA-MAZE-vivado/FPGA-MAZE-vivado.gen/sources_1/ip/end_rom_1/end_rom/end_rom_in_context.xdc rfile:../../../../../FPGA-MAZE-vivado.gen/sources_1/ip/end_rom_1/end_rom/end_rom_in_context.xdc id:2 order:EARLY scoped_inst:graphics/draw/end_inst/end_rom_inst} [current_design]
set_property SRC_FILE_INFO {cfile:d:/FPGA-MAZE-2023DD-final/FPGA-MAZE-vivado/FPGA-MAZE-vivado.gen/sources_1/ip/player_rom_1/player_rom/player_rom_in_context.xdc rfile:../../../../../FPGA-MAZE-vivado.gen/sources_1/ip/player_rom_1/player_rom/player_rom_in_context.xdc id:3 order:EARLY scoped_inst:graphics/draw/player_inst/player_rom_inst} [current_design]
set_property SRC_FILE_INFO {cfile:d:/FPGA-MAZE-2023DD-final/FPGA-MAZE-vivado/FPGA-MAZE-vivado.gen/sources_1/ip/set_rom_1/set_rom/set_rom_in_context.xdc rfile:../../../../../FPGA-MAZE-vivado.gen/sources_1/ip/set_rom_1/set_rom/set_rom_in_context.xdc id:4 order:EARLY scoped_inst:graphics/draw/set_inst/set_rom_inst} [current_design]
set_property SRC_FILE_INFO {cfile:d:/FPGA-MAZE-2023DD-final/FPGA-MAZE-vivado/FPGA-MAZE-vivado.gen/sources_1/ip/start_rom/start_rom/start_rom_in_context.xdc rfile:../../../../../FPGA-MAZE-vivado.gen/sources_1/ip/start_rom/start_rom/start_rom_in_context.xdc id:5 order:EARLY scoped_inst:graphics/draw/start_inst/start_rom_inst} [current_design]
set_property SRC_FILE_INFO {cfile:d:/FPGA-MAZE-2023DD-final/FPGA-MAZE-vivado/FPGA-MAZE-vivado.gen/sources_1/ip/wall_rom/wall_rom/wall_rom_in_context.xdc rfile:../../../../../FPGA-MAZE-vivado.gen/sources_1/ip/wall_rom/wall_rom/wall_rom_in_context.xdc id:6 order:EARLY scoped_inst:graphics/draw/wall_inst/wall_rom_inst} [current_design]
set_property SRC_FILE_INFO {cfile:d:/FPGA-MAZE-2023DD-final/FPGA-MAZE-vivado/FPGA-MAZE-vivado.gen/sources_1/ip/win_rom/win_rom/win_rom_in_context.xdc rfile:../../../../../FPGA-MAZE-vivado.gen/sources_1/ip/win_rom/win_rom/win_rom_in_context.xdc id:7 order:EARLY scoped_inst:graphics/draw/win_inst/win_rom_inst} [current_design]
set_property SRC_FILE_INFO {cfile:d:/FPGA-MAZE-2023DD-final/FPGA-MAZE-vivado/FPGA-MAZE-vivado.gen/sources_1/ip/road_rom/road_rom/road_rom_in_context.xdc rfile:../../../../../FPGA-MAZE-vivado.gen/sources_1/ip/road_rom/road_rom/road_rom_in_context.xdc id:8 order:EARLY scoped_inst:graphics/draw/road_inst/road_rom_inst} [current_design]
set_property SRC_FILE_INFO {cfile:D:/FPGA-MAZE-2023DD-final/src/Maze_constraints.xdc rfile:../../../../../../src/Maze_constraints.xdc id:9} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins graphics/draw/background_inst/background_rom_inst/clka]
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells graphics/draw/background_inst/background_rom_inst]
set_property src_info {type:SCOPED_XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins graphics/draw/end_inst/end_rom_inst/clka]
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells graphics/draw/end_inst/end_rom_inst]
set_property src_info {type:SCOPED_XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins graphics/draw/player_inst/player_rom_inst/clka]
set_property src_info {type:SCOPED_XDC file:3 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells graphics/draw/player_inst/player_rom_inst]
set_property src_info {type:SCOPED_XDC file:4 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins graphics/draw/set_inst/set_rom_inst/clka]
set_property src_info {type:SCOPED_XDC file:4 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells graphics/draw/set_inst/set_rom_inst]
set_property src_info {type:SCOPED_XDC file:5 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins graphics/draw/start_inst/start_rom_inst/clka]
set_property src_info {type:SCOPED_XDC file:5 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells graphics/draw/start_inst/start_rom_inst]
set_property src_info {type:SCOPED_XDC file:6 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins graphics/draw/wall_inst/wall_rom_inst/clka]
set_property src_info {type:SCOPED_XDC file:6 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells graphics/draw/wall_inst/wall_rom_inst]
set_property src_info {type:SCOPED_XDC file:7 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins graphics/draw/win_inst/win_rom_inst/clka]
set_property src_info {type:SCOPED_XDC file:7 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells graphics/draw/win_inst/win_rom_inst]
set_property src_info {type:SCOPED_XDC file:8 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins graphics/draw/road_inst/road_rom_inst/clka]
set_property src_info {type:SCOPED_XDC file:8 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells graphics/draw/road_inst/road_rom_inst]
set_property src_info {type:XDC file:9 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports clk]
set_property src_info {type:XDC file:9 line:8 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name clk [get_ports clk]
set_property src_info {type:XDC file:9 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS15 [get_ports rst_sys]
set_property src_info {type:XDC file:9 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports ps2_clk]
set_property src_info {type:XDC file:9 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports ps2_data]
set_property src_info {type:XDC file:9 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {Red[0]}]
set_property src_info {type:XDC file:9 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {Red[1]}]
set_property src_info {type:XDC file:9 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {Red[2]}]
set_property src_info {type:XDC file:9 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {Red[3]}]
set_property src_info {type:XDC file:9 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {Green[0]}]
set_property src_info {type:XDC file:9 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {Green[1]}]
set_property src_info {type:XDC file:9 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {Green[2]}]
set_property src_info {type:XDC file:9 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {Green[3]}]
set_property src_info {type:XDC file:9 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {Blue[0]}]
set_property src_info {type:XDC file:9 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {Blue[1]}]
set_property src_info {type:XDC file:9 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {Blue[2]}]
set_property src_info {type:XDC file:9 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {Blue[3]}]
set_property src_info {type:XDC file:9 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports HSYNC]
set_property src_info {type:XDC file:9 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports VSYNC]
set_property src_info {type:XDC file:9 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports seg_clk]
set_property src_info {type:XDC file:9 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports seg_sout]
set_property src_info {type:XDC file:9 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports seg_pen]
set_property src_info {type:XDC file:9 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports seg_clrn]
set_property src_info {type:XDC file:9 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[0]}]
set_property src_info {type:XDC file:9 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[1]}]
set_property src_info {type:XDC file:9 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[2]}]
set_property src_info {type:XDC file:9 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[3]}]
set_property src_info {type:XDC file:9 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {SEGMENT[0]}]
set_property src_info {type:XDC file:9 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {SEGMENT[1]}]
set_property src_info {type:XDC file:9 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {SEGMENT[2]}]
set_property src_info {type:XDC file:9 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {SEGMENT[3]}]
set_property src_info {type:XDC file:9 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {SEGMENT[4]}]
set_property src_info {type:XDC file:9 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {SEGMENT[5]}]
set_property src_info {type:XDC file:9 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {SEGMENT[6]}]
set_property src_info {type:XDC file:9 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {SEGMENT[7]}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells graphics/draw/background_inst/background_rom_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells graphics/draw/end_inst/end_rom_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells graphics/draw/player_inst/player_rom_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells graphics/draw/set_inst/set_rom_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells graphics/draw/start_inst/start_rom_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells graphics/draw/wall_inst/wall_rom_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells graphics/draw/win_inst/win_rom_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells graphics/draw/road_inst/road_rom_inst]
