# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/FPGA-MAZE-vivado/FPGA-MAZE-vivado.runs/synth_1/top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 4
set_param xicom.use_bs_reader 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7k160tffg676-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/FPGA-MAZE-vivado/FPGA-MAZE-vivado.cache/wt [current_project]
set_property parent.project_path C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/FPGA-MAZE-vivado/FPGA-MAZE-vivado.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/FPGA-MAZE-vivado/FPGA-MAZE-vivado.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/coe_files/award.coe
add_files C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/coe_files/end.coe
add_files C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/coe_files/enemy.coe
add_files C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/coe_files/fail.coe
add_files C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/coe_files/player.coe
add_files C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/coe_files/road.coe
add_files C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/coe_files/set.coe
add_files C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/coe_files/welcome.coe
add_files C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/coe_files/start.coe
add_files C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/coe_files/unknown.coe
add_files C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/coe_files/wall.coe
add_files C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/coe_files/background.coe
add_files C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/coe_files/win.coe
read_verilog -library xil_defaultlib {
  C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/7segment/DisplayNumber/gates/AND_GATE.v
  C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/7segment/DisplayNumber/gates/AND_GATE_3_INPUTS.v
  C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/7segment/DisplayNumber/gates/AND_GATE_4_INPUTS.v
  C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/Counter/Counter.v
  C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/Counter/DisplayNumber.v
  C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/Counter/DisplaySync.v
  C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/7segment/SSeg_Dev/Hex2Seg.v
  C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/7segment/SSeg_Dev/HexTo8SEG.v
  C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/7segment/DisplayNumber/circuit/Mux4to1.v
  C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/Counter/Mux4to1b4.v
  C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/Counter/My74LS161.v
  C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/7segment/DisplayNumber/circuit/MyMC14495.v
  C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/7segment/DisplayNumber/gates/OR_GATE.v
  C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/7segment/DisplayNumber/gates/OR_GATE_3_INPUTS.v
  C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/7segment/DisplayNumber/gates/OR_GATE_4_INPUTS.v
  C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/7segment/P2S_io.v
  C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/7segment/SSeg_Dev/Sseg_Dev.v
  C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/7segment/alter_size_display.v
  C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/picture_ip_wrapper/background_wrapper.v
  C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/Counter/clk_div_10ms.v
  C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/Counter/clkdiv.v
  C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/src/clkdiv_25mhz.v
  C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/src/create_map.v
  C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/7segment/display_level_num.v
  C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/src/draw.v
  C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/picture_ip_wrapper/end_wrapper.v
  C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/src/fsm.v
  C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/src/graphics.v
  C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/src/input.v
  C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/src/move.v
  C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/picture_ip_wrapper/player_wrapper.v
  C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/src/ps2.v
  C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/picture_ip_wrapper/road_wrapper.v
  C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/picture_ip_wrapper/set_wrapper.v
  C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/picture_ip_wrapper/start_wrapper.v
  C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/picture_ip_wrapper/unknown_wrapper.v
  C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/src/vgac.v
  C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/picture_ip_wrapper/wall_wrapper.v
  C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/picture_ip_wrapper/win_wrapper.v
  C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/src/top.v
}
read_ip -quiet C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/FPGA-MAZE-vivado/FPGA-MAZE-vivado.srcs/sources_1/ip/background_rom_1/background_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/FPGA-MAZE-vivado/FPGA-MAZE-vivado.gen/sources_1/ip/background_rom_1/background_rom_ooc.xdc]

read_ip -quiet C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/FPGA-MAZE-vivado/FPGA-MAZE-vivado.srcs/sources_1/ip/end_rom_1/end_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/FPGA-MAZE-vivado/FPGA-MAZE-vivado.gen/sources_1/ip/end_rom_1/end_rom_ooc.xdc]

read_ip -quiet C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/FPGA-MAZE-vivado/FPGA-MAZE-vivado.srcs/sources_1/ip/player_rom_1/player_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/FPGA-MAZE-vivado/FPGA-MAZE-vivado.gen/sources_1/ip/player_rom_1/player_rom_ooc.xdc]

read_ip -quiet C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/FPGA-MAZE-vivado/FPGA-MAZE-vivado.srcs/sources_1/ip/set_rom_1/set_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/FPGA-MAZE-vivado/FPGA-MAZE-vivado.gen/sources_1/ip/set_rom_1/set_rom_ooc.xdc]

read_ip -quiet C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/FPGA-MAZE-vivado/FPGA-MAZE-vivado.srcs/sources_1/ip/start_rom_1/start_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/FPGA-MAZE-vivado/FPGA-MAZE-vivado.gen/sources_1/ip/start_rom/start_rom_ooc.xdc]

read_ip -quiet C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/FPGA-MAZE-vivado/FPGA-MAZE-vivado.srcs/sources_1/ip/unknown_rom_1/unknown_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/FPGA-MAZE-vivado/FPGA-MAZE-vivado.gen/sources_1/ip/unknown_rom/unknown_rom_ooc.xdc]

read_ip -quiet C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/FPGA-MAZE-vivado/FPGA-MAZE-vivado.srcs/sources_1/ip/wall_rom_1/wall_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/FPGA-MAZE-vivado/FPGA-MAZE-vivado.gen/sources_1/ip/wall_rom/wall_rom_ooc.xdc]

read_ip -quiet C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/FPGA-MAZE-vivado/FPGA-MAZE-vivado.srcs/sources_1/ip/win_rom_1/win_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/FPGA-MAZE-vivado/FPGA-MAZE-vivado.gen/sources_1/ip/win_rom/win_rom_ooc.xdc]

read_ip -quiet C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/FPGA-MAZE-vivado/FPGA-MAZE-vivado.srcs/sources_1/ip/road_rom_2/road_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/FPGA-MAZE-vivado/FPGA-MAZE-vivado.gen/sources_1/ip/road_rom/road_rom_ooc.xdc]

read_edif C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/7segment/P2S.edf
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/src/Maze_constraints.xdc
set_property used_in_implementation false [get_files C:/Users/22143/Downloads/FPGA-MAZE-2023DD-final/src/Maze_constraints.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top top -part xc7k160tffg676-2L
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
