# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/FPGA-MAZE-2023DD-final/FPGA-MAZE-vivado/FPGA-MAZE-vivado.srcs/sources_1/ip/player_rom_1/player_rom.xci
# IP: The module: 'player_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA-MAZE-2023DD-final/FPGA-MAZE-vivado/FPGA-MAZE-vivado.gen/sources_1/ip/player_rom_1/player_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'player_rom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/FPGA-MAZE-2023DD-final/FPGA-MAZE-vivado/FPGA-MAZE-vivado.srcs/sources_1/ip/player_rom_1/player_rom.xci
# IP: The module: 'player_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA-MAZE-2023DD-final/FPGA-MAZE-vivado/FPGA-MAZE-vivado.gen/sources_1/ip/player_rom_1/player_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'player_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
